"""Add UserRole Enum

Revision ID: 39c0f52e4fc6
Revises: a8b6082a41d5
Create Date: 2026-06-20 12:33:05.830860
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c0f52e4fc6'
down_revision = 'a8b6082a41d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'loan_officer'")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE")
    
    # Sanitize any existing invalid roles from previous scripts
    op.execute("UPDATE users SET role = 'collector' WHERE role = 'cashier'")
    op.execute("UPDATE users SET role = 'administrator' WHERE role = 'auditor'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS is_active")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS role")
    # ### end Alembic commands ###
