"""Add company details to GlobalSettings

Revision ID: a8b6082a41d5
Revises: 20260425_0004
Create Date: 2026-06-19 17:48:35.019636
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b6082a41d5'
down_revision = '20260425_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS app_name VARCHAR(100) DEFAULT 'PawnPlatform' NOT NULL")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_name VARCHAR(150)")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_document_type VARCHAR(20)")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_document_number VARCHAR(50)")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_address VARCHAR(200)")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_phone VARCHAR(50)")
    op.execute("ALTER TABLE global_settings ADD COLUMN IF NOT EXISTS company_email VARCHAR(100)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'company_email')
    op.drop_column('global_settings', 'company_phone')
    op.drop_column('global_settings', 'company_address')
    op.drop_column('global_settings', 'company_document_number')
    op.drop_column('global_settings', 'company_document_type')
    op.drop_column('global_settings', 'company_name')
    op.drop_column('global_settings', 'app_name')
    # ### end Alembic commands ###
