"""Add company details to GlobalSettings

Revision ID: a8b6082a41d5
Revises: 20260425_0004
Create Date: 2026-06-19 17:48:35.019636
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b6082a41d5'
down_revision = '20260425_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('app_name', sa.String(length=100), nullable=False, server_default='PawnPlatform'))
    op.add_column('global_settings', sa.Column('company_name', sa.String(length=150), nullable=True))
    op.add_column('global_settings', sa.Column('company_document_type', sa.String(length=20), nullable=True))
    op.add_column('global_settings', sa.Column('company_document_number', sa.String(length=50), nullable=True))
    op.add_column('global_settings', sa.Column('company_address', sa.String(length=200), nullable=True))
    op.add_column('global_settings', sa.Column('company_phone', sa.String(length=50), nullable=True))
    op.add_column('global_settings', sa.Column('company_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'company_email')
    op.drop_column('global_settings', 'company_phone')
    op.drop_column('global_settings', 'company_address')
    op.drop_column('global_settings', 'company_document_number')
    op.drop_column('global_settings', 'company_document_type')
    op.drop_column('global_settings', 'company_name')
    op.drop_column('global_settings', 'app_name')
    # ### end Alembic commands ###
