"""add_creator_tracking

Revision ID: d053de0e094c
Revises: f5272c107625
Create Date: 2026-06-20 13:10:07.987322
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd053de0e094c'
down_revision = 'f5272c107625'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['created_by_id'], ['id'])
    op.add_column('loans', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'created_by_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'created_by_id')
    # ### end Alembic commands ###
