"""add_creator_tracking

Revision ID: d053de0e094c
Revises: f5272c107625
Create Date: 2026-06-20 13:10:07.987322
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd053de0e094c'
down_revision = 'f5272c107625'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by_id INTEGER")
    op.execute("ALTER TABLE loans ADD COLUMN IF NOT EXISTS created_by_id INTEGER")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'customers' AND constraint_name = 'customers_created_by_id_fkey'
            ) THEN
                ALTER TABLE customers ADD CONSTRAINT customers_created_by_id_fkey
                    FOREIGN KEY (created_by_id) REFERENCES users (id);
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'loans' AND constraint_name = 'loans_created_by_id_fkey'
            ) THEN
                ALTER TABLE loans ADD CONSTRAINT loans_created_by_id_fkey
                    FOREIGN KEY (created_by_id) REFERENCES users (id);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'created_by_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'created_by_id')
    # ### end Alembic commands ###
