"""add_sale_fields_to_collateral

Revision ID: d94e8344fe17
Revises: 4204eb05a02c
Create Date: 2026-06-20 16:57:11.702667
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94e8344fe17'
down_revision = '4204eb05a02c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collateral_items', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('collateral_items', sa.Column('sold_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'defaulted'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collateral_items', 'sold_at')
    op.drop_column('collateral_items', 'sale_price')
    # ### end Alembic commands ###
