"""add user profile fields

Revision ID: f5272c107625
Revises: 39c0f52e4fc6
Create Date: 2026-06-20 12:51:29.562996
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5272c107625'
down_revision = '39c0f52e4fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(100) DEFAULT '' NOT NULL")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(120) DEFAULT '' NOT NULL")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(30) DEFAULT '' NOT NULL")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS document_number VARCHAR(40) DEFAULT '' NOT NULL")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS address VARCHAR(200) DEFAULT '' NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'document_number')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
