<template>
  <div v-if="show && loan" class="modal-backdrop" @click.self="closeModal">
    <div class="modal-panel card modal-panel-lg">
      <div class="modal-header">
        <h3>{{ t('loans.loanDetail') }}</h3>
        <div class="form-inline">
          <a :href="'/print/invoice/loan/' + loan.id" target="_blank" class="btn btn-secondary btn-icon" :title="t('common.printInvoice')" style="text-decoration: none;">
            <Printer :size="16" />
          </a>
          <button class="btn btn-secondary btn-icon" type="button" @click="closeModal">
            <X :size="16" />
          </button>
        </div>
      </div>

      <p class="muted mt-16">{{ t('loans.selectedLoan', { id: loan.id }) }}</p>

      <div class="grid grid-4 mt-16">
        <div class="card stat-card stat-accent-indigo">
          <p class="stat-label">{{ t('common.customer') }}</p>
          <p class="stat-value">{{ customerName || t('common.unknown') }}</p>
        </div>
        <div class="card stat-card stat-accent-blue">
          <p class="stat-label">{{ t('common.type') }}</p>
          <p class="stat-value">
            {{ loan.loanType === 'pawn' ? t('common.pawn') : t('common.personal') }}
          </p>
        </div>
        <div class="card stat-card stat-accent-green">
          <p class="stat-label">{{ t('common.principal') }}</p>
          <p class="stat-value">{{ formatCurrency(loan.principalAmount) }}</p>
        </div>
        <div class="card stat-card stat-accent-amber">
          <p class="stat-label">{{ t('loans.outstanding') }}</p>
          <p class="stat-value">{{ formatCurrency(loan.outstandingPrincipal) }}</p>
        </div>
      </div>

      <div class="stats-inline mt-16">
        <span class="pill">{{ t('common.status') }}: {{ t(`common.${loan.status}`) }}</span>
        <span class="pill" :title="t('loans.graceDaysHelp')">{{ t('loans.dueDay') }}: {{ loan.dueDay }}</span>
        <span class="pill">{{ t('loans.rate') }}: {{ loan.monthlyInterestRate }}%</span>
        <span class="pill">{{ t('common.date') }}: {{ formatDateDMY(loan.disbursementDate) }}</span>
        <span class="pill">{{ t('common.createdBy', 'Generated by') }}: {{ loan?.created_by?.full_name || loan?.created_by?.username || '-' }}</span>
      </div>

      <div v-if="!editingDescription" class="mt-16 stats-inline">
        <span class="muted"><strong>{{ t('loans.description') }}:</strong> {{ loan.description || t('loans.noDescription') }}</span>
        <button class="btn btn-secondary" type="button" @click="startEditDescription">
          <Pencil :size="14" />
          {{ t('common.edit') }}
        </button>
      </div>
      <div v-else class="mt-16">
        <label>
          {{ t('loans.description') }}
          <textarea v-model="descriptionDraft" rows="3" :placeholder="t('loans.descriptionPlaceholder')" />
        </label>
        <div class="form-inline mt-8">
          <button class="btn" type="button" :disabled="isSavingDescription" @click="saveDescription">
            <Save :size="14" />
            {{ t('common.save') }}
          </button>
          <button class="btn btn-secondary" type="button" @click="cancelEditDescription">
            <X :size="14" />
            {{ t('common.cancel') }}
          </button>
        </div>
      </div>

      <div v-if="financialDataLoading" class="mt-16 text-center muted">
        {{ t('common.loading') }}
      </div>
      <div v-else>
        <div class="grid grid-2 mt-16">
          <div class="card stat-card stat-accent-amber">
            <p class="stat-label">{{ t('payments.totalPendingInterest') }}</p>
            <p class="stat-value">{{ formatCurrency(totalPendingInterest) }}</p>
          </div>
          <div class="card stat-card stat-accent-blue">
            <p class="stat-label">{{ t('payments.totalPendingPenalty') }}</p>
            <p class="stat-value">{{ formatCurrency(totalPendingPenalty) }}</p>
          </div>
        </div>

        <div class="mt-16">
          <h3>{{ t('loans.loanPayments') }}</h3>
          <p class="muted" v-if="!payments.length">{{ t('loans.noLoanPayments') }}</p>
          <div v-else class="table-wrap mt-16">
            <table>
              <thead>
                <tr>
                  <th>{{ t('common.date') }}</th>
                  <th>{{ t('common.total') }}</th>
                  <th>{{ t('payments.penalty') }}</th>
                  <th>{{ t('common.interest') }}</th>
                  <th>{{ t('common.fees') }}</th>
                  <th>{{ t('common.principal') }}</th>
                  <th>{{ t('common.method') }}</th>
                  <th>{{ t('payments.notes') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="payment in paginatedLoanPayments" :key="payment.id">
                  <td>{{ formatDateDMY(payment.paymentDate) }}</td>
                  <td>{{ formatCurrency(payment.totalAmount) }}</td>
                  <td>{{ formatCurrency(payment.allocatedToPenalty) }}</td>
                  <td>{{ formatCurrency(payment.allocatedToInterest) }}</td>
                  <td>{{ formatCurrency(payment.allocatedToFees) }}</td>
                  <td>{{ formatCurrency(payment.allocatedToPrincipal) }}</td>
                  <td>{{ getPaymentMethodLabel(payment.paymentMethod) }}</td>
                  <td class="muted">{{ payment.notes || '-' }}</td>
                </tr>
              </tbody>
            </table>
            <Pagination v-model="loanPaymentsCurrentPage" :totalItems="payments.length" :itemsPerPage="10" />
          </div>
        </div>

        <div class="mt-16">
          <h3>{{ t('loans.loanCollateral') }}</h3>
          <p class="muted" v-if="!collaterals.length">{{ t('loans.noLoanCollateral') }}</p>
          <div v-else class="table-wrap mt-16">
            <table>
              <thead>
                <tr>
                  <th>{{ t('common.id') }}</th>
                  <th>{{ t('common.description') }}</th>
                  <th>{{ t('collateral.appraisedValue') }}</th>
                  <th>{{ t('collateral.custodyCode') }}</th>
                  <th>{{ t('collateral.location') }}</th>
                  <th>{{ t('common.status') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in paginatedLoanCollateral" :key="item.id">
                  <td>#{{ item.id }}</td>
                  <td>{{ item.description }}</td>
                  <td>{{ formatCurrency(item.appraisedValue) }}</td>
                  <td>{{ item.custodyCode }}</td>
                  <td>{{ item.storageLocation }}</td>
                  <td>{{ item.status === 'in-custody' ? t('common.inCustody') : t(`common.${item.status}`) }}</td>
                </tr>
              </tbody>
            </table>
            <Pagination v-model="loanCollateralsCurrentPage" :totalItems="collaterals.length" :itemsPerPage="10" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { Printer, X, Pencil, Save } from 'lucide-vue-next'
import { usePlatformStore } from '../stores/platformStore'

import Pagination from './Pagination.vue'
import type { Loan, Payment, CollateralItem } from '../types/domain'

const props = defineProps<{
  show: boolean
  loan: Loan | null
  customerName: string
  payments: Payment[]
  collaterals: CollateralItem[]
  financialDataLoading: boolean
  totalPendingInterest: number
  totalPendingPenalty: number
}>()

const emit = defineEmits<{
  (e: 'close'): void
}>()

const { t } = useI18n()
const store = usePlatformStore()

const loanPaymentsCurrentPage = ref(1)
const loanCollateralsCurrentPage = ref(1)

const locale = useI18n().locale
const currencyCode = computed(() => store.state.globalSettings?.currencyCode ?? 'COP')

const formatCurrency = (amount: number) =>
  new Intl.NumberFormat(locale.value === 'es' ? 'es-MX' : 'en-US', {
    style: 'currency',
    currency: currencyCode.value
  }).format(amount)

const formatDateDMY = (dateString: string) => {
  if (!dateString) return '-'
  const [y, m, d] = dateString.split('-')
  return `${d}/${m}/${y}`
}


const paginatedLoanPayments = computed(() => {
  const start = (loanPaymentsCurrentPage.value - 1) * 10
  return props.payments.slice(start, start + 10)
})

const paginatedLoanCollateral = computed(() => {
  const start = (loanCollateralsCurrentPage.value - 1) * 10
  return props.collaterals.slice(start, start + 10)
})

const getPaymentMethodLabel = (method: string) => {
  if (method === 'cash') return t('common.cash')
  if (method === 'bank-transfer') return t('common.bankTransfer')
  return t('common.other')
}

const closeModal = () => {
  emit('close')
  editingDescription.value = false
  descriptionDraft.value = ''
}

// Description editing
const editingDescription = ref(false)
const descriptionDraft = ref('')
const isSavingDescription = ref(false)

const startEditDescription = () => {
  descriptionDraft.value = props.loan?.description ?? ''
  editingDescription.value = true
}

const cancelEditDescription = () => {
  editingDescription.value = false
}

const saveDescription = async () => {
  if (!props.loan || isSavingDescription.value) return
  try {
    isSavingDescription.value = true
    await store.updateLoan({
      id: props.loan.id,
      loanType: props.loan.loanType,
      principalAmount: props.loan.principalAmount,
      outstandingPrincipal: props.loan.outstandingPrincipal,
      monthlyInterestRate: props.loan.monthlyInterestRate,
      latePenaltyRate: props.loan.latePenaltyRate,
      disbursementDate: props.loan.disbursementDate,
      dueDay: props.loan.dueDay,
      status: props.loan.status,
      description: descriptionDraft.value,
    })
    editingDescription.value = false
  } catch (error) {
    console.error('Failed to update loan description', error)
  } finally {
    isSavingDescription.value = false
  }
}

watch(() => props.show, (newVal) => {
  if (newVal) {
    editingDescription.value = false
    loanPaymentsCurrentPage.value = 1
    loanCollateralsCurrentPage.value = 1
  }
})
</script>
