<template>
  <div v-if="show && loan" class="modal-backdrop" @click.self="closeModal">
    <div class="modal-panel card modal-panel-lg">
      <div class="modal-header">
        <h3>{{ t('loans.loanDetail') }}</h3>
        <div class="form-inline">
          <!-- `.btn-danger` already carries this colour; the inline style repeated it in the
               old palette's red, and `.btn-sm` was never a class anywhere. -->
          <button v-if="canForeclose" class="btn btn-danger" type="button" :disabled="isForeclosing" @click="confirmForeclose">
            <AlertTriangle :size="14" aria-hidden="true" />
            <span v-if="isForeclosing" class="spinner-small"></span>
            <span v-else>{{ t('loans.forecloseLoan') }}</span>
          </button>
          <a :href="'/print/invoice/loan/' + loan.id" target="_blank" class="btn btn-secondary btn-icon" :title="t('common.printInvoice')">
            <Printer :size="16" aria-hidden="true" />
          </a>
          <button class="btn btn-secondary btn-icon" type="button" @click="closeModal">
            <X :size="16" />
          </button>
        </div>
      </div>

      <p v-if="forecloseError" class="notice notice-error mt-16">{{ forecloseError }}</p>

      <p class="muted mt-16">{{ t('loans.selectedLoan', { id: loan.id }) }}</p>

      <div class="grid grid-4 mt-16">
        <div class="card stat-card stat-accent-indigo">
          <p class="stat-label">{{ t('common.customer') }}</p>
          <p class="stat-value">{{ customerName || t('common.unknown') }}</p>
        </div>
        <div class="card stat-card stat-accent-blue">
          <p class="stat-label">{{ t('common.type') }}</p>
          <p class="stat-value">
            {{ loan.loanType === 'pawn' ? t('common.pawn') : t('common.personal') }}
          </p>
        </div>
        <div class="card stat-card stat-accent-green">
          <p class="stat-label">{{ t('common.principal') }}</p>
          <p class="stat-value">{{ formatCurrency(loan.principalAmount) }}</p>
        </div>
        <div class="card stat-card stat-accent-amber">
          <p class="stat-label">{{ t('loans.outstanding') }}</p>
          <p class="stat-value">{{ formatCurrency(loan.outstandingPrincipal) }}</p>
        </div>
      </div>

      <div class="stats-inline mt-16">
        <span class="pill">{{ t('common.status') }}: {{ t(`common.${loan.status}`) }}</span>
        <!-- The billing day belongs to the loan; grace days are portfolio policy and live
             in Settings, so showing them per loan said nothing about this one. -->
        <span class="pill" v-if="billingDay !== null">{{ t('common.paymentDay') }}: {{ billingDay }}</span>
        <span class="pill">{{ t('loans.rate') }}: {{ loan.monthlyInterestRate }}%</span>
        <span class="pill">{{ t('common.date') }}: {{ formatDateDMY(loan.disbursementDate) }}</span>
        <span class="pill">{{ t('common.createdBy', 'Generated by') }}: {{ loan?.created_by?.full_name || loan?.created_by?.username || '-' }}</span>
      </div>

      <div v-if="!editingDescription" class="mt-16 stats-inline">
        <span class="muted"><strong>{{ t('loans.description') }}:</strong> {{ loan.description || t('loans.noDescription') }}</span>
        <button class="btn btn-secondary" type="button" @click="startEditDescription">
          <Pencil :size="14" />
          {{ t('common.edit') }}
        </button>
      </div>
      <div v-else class="mt-16">
        <label>
          {{ t('loans.description') }}
          <textarea v-model="descriptionDraft" rows="3" :placeholder="t('loans.descriptionPlaceholder')" />
        </label>
        <div class="form-inline mt-8">
          <button class="btn" type="button" :disabled="isSavingDescription" @click="saveDescription">
            <Save :size="14" />
            {{ t('common.save') }}
          </button>
          <button class="btn btn-secondary" type="button" @click="cancelEditDescription">
            <X :size="14" />
            {{ t('common.cancel') }}
          </button>
        </div>
      </div>

      <!-- Skeleton tiles in the shape of the two figures that are coming, so the modal does
           not resize under the reader the moment they arrive. -->
      <div v-if="financialDataLoading" class="grid grid-2 mt-16" role="status" :aria-label="t('common.loading')">
        <div class="card stat-card">
          <span class="skeleton skeleton-text" style="width: 45%"></span>
          <span class="skeleton skeleton-text" style="width: 70%; height: 1.2rem"></span>
        </div>
        <div class="card stat-card">
          <span class="skeleton skeleton-text" style="width: 45%"></span>
          <span class="skeleton skeleton-text" style="width: 70%; height: 1.2rem"></span>
        </div>
      </div>
      <div v-else>
        <div class="grid grid-2 mt-16">
          <div class="card stat-card stat-accent-amber">
            <p class="stat-label">{{ t('payments.totalPendingInterest') }}</p>
            <p class="stat-value">{{ formatCurrency(totalPendingInterest) }}</p>
          </div>
          <div class="card stat-card stat-accent-blue">
            <p class="stat-label">{{ t('payments.totalPendingPenalty') }}</p>
            <p class="stat-value">{{ formatCurrency(totalPendingPenalty) }}</p>
          </div>
        </div>

        <div class="mt-16">
          <h3>{{ t('loans.loanPayments') }}</h3>
          <p class="muted" v-if="!payments.length">{{ t('loans.noLoanPayments') }}</p>
          <div v-else class="table-wrap mt-16">
            <table>
              <thead>
                <tr>
                  <th>{{ t('common.date') }}</th>
                  <th>{{ t('common.total') }}</th>
                  <th>{{ t('payments.penalty') }}</th>
                  <th>{{ t('common.interest') }}</th>
                  <th>{{ t('common.fees') }}</th>
                  <th>{{ t('common.principal') }}</th>
                  <th>{{ t('common.method') }}</th>
                  <th>{{ t('payments.notes') }}</th>
                  <th>{{ t('common.actions') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="payment in paginatedLoanPayments" :key="payment.id">
                  <td :data-label="t('common.date')">{{ formatDateDMY(payment.paymentDate) }}</td>
                  <td :data-label="t('common.total')">{{ formatCurrency(payment.totalAmount) }}</td>
                  <td :data-label="t('payments.penalty')">{{ formatCurrency(payment.allocatedToPenalty) }}</td>
                  <td :data-label="t('common.interest')">{{ formatCurrency(payment.allocatedToInterest) }}</td>
                  <td :data-label="t('common.fees')">{{ formatCurrency(payment.allocatedToFees) }}</td>
                  <td :data-label="t('common.principal')">{{ formatCurrency(payment.allocatedToPrincipal) }}</td>
                  <td :data-label="t('common.method')">{{ getPaymentMethodLabel(payment.paymentMethod) }}</td>
                  <td class="muted" :data-label="t('payments.notes')">
                    {{ payment.notes || '-' }}
                    <div v-if="payment.isReversed" class="pill pill-overdue mt-1">
                      {{ t('payments.reversed') }}<template v-if="payment.reversalReason">: {{ payment.reversalReason }}</template>
                    </div>
                  </td>
                  <td>
                    <button
                      v-if="hasRole([UserRole.Administrator, UserRole.LoanOfficer])"
                      class="btn btn-danger btn-icon"
                      type="button"
                      :title="t('payments.deletePayment')"
                      :aria-label="t('payments.deletePayment')"
                      :disabled="payment.isReversed"
                      @click="paymentPendingReversal = payment"
                    >
                      <Trash2 :size="14" />
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
            <Pagination v-model="loanPaymentsCurrentPage" :totalItems="payments.length" :itemsPerPage="10" />
          </div>
        </div>

        <div class="mt-16">
          <h3>{{ t('loans.loanCollateral') }}</h3>
          <p class="muted" v-if="!collaterals.length">{{ t('loans.noLoanCollateral') }}</p>
          <div v-else class="table-wrap mt-16">
            <table>
              <thead>
                <tr>
                  <th>{{ t('common.id') }}</th>
                  <th>{{ t('common.description') }}</th>
                  <th>{{ t('collateral.appraisedValue') }}</th>
                  <th>{{ t('collateral.custodyCode') }}</th>
                  <th>{{ t('collateral.location') }}</th>
                  <th>{{ t('common.status') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in paginatedLoanCollateral" :key="item.id">
                  <td :data-label="t('common.id')">#{{ item.id }}</td>
                  <td :data-label="t('common.description')">{{ item.description }}</td>
                  <td :data-label="t('collateral.appraisedValue')">{{ formatCurrency(item.appraisedValue) }}</td>
                  <td :data-label="t('collateral.custodyCode')">{{ item.custodyCode }}</td>
                  <td :data-label="t('collateral.location')">{{ item.storageLocation }}</td>
                  <td :data-label="t('common.status')">{{ item.status === 'in-custody' ? t('common.inCustody') : t(`common.${item.status}`) }}</td>
                </tr>
              </tbody>
            </table>
            <Pagination v-model="loanCollateralsCurrentPage" :totalItems="collaterals.length" :itemsPerPage="10" />
          </div>
        </div>
      </div>
    </div>
  </div>

  <PaymentReversalModal
    :payment="paymentPendingReversal"
    @close="paymentPendingReversal = null"
    @deleted="onPaymentDeleted"
  />
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useConfirmDialog } from '../composables/useConfirmDialog'
import { Printer, X, Pencil, Save, AlertTriangle, Trash2 } from 'lucide-vue-next'
import { usePlatformStore } from '../stores/platformStore'

import Pagination from './Pagination.vue'
import { formatCurrency } from '../utils/currency'
/* `formatDateDMY` was written out again in this file and hard-coded `DD/MM/YYYY`, so the
   loan detail ignored `GlobalSettings.dateFormat` the same way the collateral screen did. */
import { billingAnchorDay, formatDateDMY } from '../utils/date'
import PaymentReversalModal from './PaymentReversalModal.vue'
import { useAuthState, UserRole } from '../modules/authentication/authState'
import type { Loan, Payment, CollateralItem } from '../types/domain'

const props = defineProps<{
  show: boolean
  loan: Loan | null
  customerName: string
  payments: Payment[]
  collaterals: CollateralItem[]
  financialDataLoading: boolean
  totalPendingInterest: number
  totalPendingPenalty: number
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'payments-changed'): void
}>()

const { t } = useI18n()
  const { confirm: confirmDialog } = useConfirmDialog()
const store = usePlatformStore()

const { hasRole } = useAuthState()

const paymentPendingReversal = ref<Payment | null>(null)

// The parent owns the payments list, so a deletion has to bubble up for it to reload.
const onPaymentDeleted = async () => {
  await store.refreshAll()
  emit('payments-changed')
}

const billingDay = computed(() =>
  props.loan ? billingAnchorDay(props.loan.disbursementDate) : null
)

const loanPaymentsCurrentPage = ref(1)
const loanCollateralsCurrentPage = ref(1)

const paginatedLoanPayments = computed(() => {
  const start = (loanPaymentsCurrentPage.value - 1) * 10
  return props.payments.slice(start, start + 10)
})

const paginatedLoanCollateral = computed(() => {
  const start = (loanCollateralsCurrentPage.value - 1) * 10
  return props.collaterals.slice(start, start + 10)
})

const getPaymentMethodLabel = (method: string) => {
  if (method === 'cash') return t('common.cash')
  if (method === 'bank-transfer') return t('common.bankTransfer')
  return t('common.other')
}

const closeModal = () => {
  emit('close')
  editingDescription.value = false
  descriptionDraft.value = ''
}

// Description editing

const isForeclosing = ref(false)

const canForeclose = computed(() => {
  return props.loan?.loanType === 'pawn' && 
         ['active', 'overdue'].includes(props.loan?.status)
})

const forecloseError = ref('')

const confirmForeclose = async () => {
  if (await confirmDialog(t('collaterals.foreclosureWarning'))) {
    if (!props.loan) return
    try {
      isForeclosing.value = true
      forecloseError.value = ''
      await store.forecloseLoan(props.loan.id)
      /* Was `window.location.reload()` with the comment "simple refresh to update tables".
         It threw away the operator's filters, sort order and page — and, when this modal was
         opened from a customer detail, the whole customer they were working in — immediately
         after the most consequential action in the product. `refreshAll` is what the store
         has for this, and the parent already listens for the event. */
      await store.refreshAll()
      emit('payments-changed')
      emit('close')
    } catch (e: any) {
      // Was a native `alert('Error: ' + ...)`, in English regardless of locale.
      forecloseError.value = e?.response?.data?.detail || e?.message || t('loans.forecloseFailed')
    } finally {
      isForeclosing.value = false
    }
  }
}

const editingDescription = ref(false)
const descriptionDraft = ref('')
const isSavingDescription = ref(false)

const startEditDescription = () => {
  descriptionDraft.value = props.loan?.description ?? ''
  editingDescription.value = true
}

const cancelEditDescription = () => {
  editingDescription.value = false
}

const saveDescription = async () => {
  if (!props.loan || isSavingDescription.value) return
  try {
    isSavingDescription.value = true
    await store.updateLoan({
      id: props.loan.id,
      loanType: props.loan.loanType,
      principalAmount: props.loan.principalAmount,
      outstandingPrincipal: props.loan.outstandingPrincipal,
      monthlyInterestRate: props.loan.monthlyInterestRate,
      latePenaltyRate: props.loan.latePenaltyRate,
      disbursementDate: props.loan.disbursementDate,
      status: props.loan.status,
      description: descriptionDraft.value,
    })
    editingDescription.value = false
  } catch (error) {
    console.error('Failed to update loan description', error)
  } finally {
    isSavingDescription.value = false
  }
}

watch(() => props.show, (newVal) => {
  if (newVal) {
    editingDescription.value = false
    loanPaymentsCurrentPage.value = 1
    loanCollateralsCurrentPage.value = 1
  }
})
</script>
