#!/usr/bin/env bash
#
# Rolls the production stack on the droplet forward to $IMAGE_TAG.
#
# This is the ONE copy of the deploy procedure: the release workflow, the manual
# "Deploy To Droplet" workflow and an operator on the box all run this same script, so there is
# no second version to drift. It is idempotent — running it twice deploys the same thing twice.
#
# It renders `.env.production` from two sources on every run: `production.env` next to this
# file (versioned, non-secret) and three secrets from the environment. That file is generated,
# never hand-maintained: editing it on the droplet is overwritten by the next deploy.
#
# Required in the environment:
#   POSTGRES_PASSWORD  JWT_SECRET_KEY  ADMIN_PASSWORD
# Optional:
#   IMAGE_TAG   image tag to deploy (default: latest)
#   GHCR_USER / GHCR_TOKEN   registry login, only needed if the packages are private
#   HOSTINGER_MAIL_API_TOKEN  outbound mail; unset means the app sends none, which is a
#                             supported state and must not stop a deploy
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$APP_DIR"

BASE_ENV="deploy/digitalocean/production.env"
TARGET_ENV=".env.production"
COMPOSE_FILE="docker-compose.prod.yml"
IMAGE_TAG="${IMAGE_TAG:-latest}"

for name in POSTGRES_PASSWORD JWT_SECRET_KEY ADMIN_PASSWORD; do
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required secret: $name (set it as a GitHub Actions secret)." >&2
    exit 1
  fi
done

# The API refuses to boot in production with the published default, so catching it here turns a
# crash-looping container into a one-line failure.
if [[ "$JWT_SECRET_KEY" == "change_this_in_production" ]]; then
  echo "JWT_SECRET_KEY still holds the published development default. Generate one with 'openssl rand -hex 48'." >&2
  exit 1
fi

test -f "$BASE_ENV" || { echo "Missing $BASE_ENV" >&2; exit 1; }

# Read from the versioned file rather than sourcing it: sourcing would execute it, and an
# unquoted value with a space in it (APP_NAME) would run as a command.
read_base() { sed -n "s/^$1=//p" "$BASE_ENV" | tail -n 1; }

POSTGRES_USER="$(read_base POSTGRES_USER)"
POSTGRES_DB="$(read_base POSTGRES_DB)"
DOMAIN="$(read_base DOMAIN)"
for name in POSTGRES_USER POSTGRES_DB DOMAIN; do
  if [[ -z "${!name}" ]]; then
    echo "Missing $name in $BASE_ENV" >&2
    exit 1
  fi
done

echo "Rendering $TARGET_ENV for $DOMAIN (image tag: $IMAGE_TAG)"

# 077 so the rendered file — which holds the database password and the signing key — is not
# world-readable, and a temp file so a failure never leaves a half-written env behind.
umask 077
{
  echo "# GENERATED by deploy/digitalocean/remote_deploy.sh on every deploy. Do not edit here:"
  echo "# non-secret values live in $BASE_ENV (versioned), secrets in GitHub Actions secrets."
  echo
  cat "$BASE_ENV"
  echo
  echo "# ─── Injected at deploy time ───"
  echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
  echo "JWT_SECRET_KEY=$JWT_SECRET_KEY"
  echo "ADMIN_PASSWORD=$ADMIN_PASSWORD"
  echo "HOSTINGER_MAIL_API_TOKEN=${HOSTINGER_MAIL_API_TOKEN:-}"
  # Composed here so the credentials exist in exactly one place. Keeping a second literal copy
  # of the password inside a URL is how the two silently stop matching.
  echo "DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
  # Same reason, and it matters more: this is what a password-recovery link points at. Derived
  # from DOMAIN so changing the domain cannot leave the emails aimed at the old one.
  echo "FRONTEND_URL=https://${DOMAIN}"
} > "$TARGET_ENV.tmp"
mv "$TARGET_ENV.tmp" "$TARGET_ENV"
chmod 600 "$TARGET_ENV"

if [[ -n "${GHCR_TOKEN:-}" ]]; then
  echo "$GHCR_TOKEN" | docker login ghcr.io -u "${GHCR_USER:-x-access-token}" --password-stdin
fi

compose() {
  IMAGE_TAG="$IMAGE_TAG" docker compose --env-file "$TARGET_ENV" -f "$COMPOSE_FILE" "$@"
}

# Pull first, start second: the running containers keep serving while the layers download.
compose pull
compose up -d --remove-orphans

docker image prune -f >/dev/null

echo
compose ps
echo
echo "Deployed image tag $IMAGE_TAG — https://$DOMAIN"
